spring:
  application:
    name: Edge-Server
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
          filters:
            - RewritePath=/events/(?<segment>.*), /${segment}
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

